__author__ = 'Adam'

"""
Here  you can hard-code some specific constants
"""

import os
import random


DATA_FILE_NAME = 'data.csv'
DATA_FILE_PATH = os.path.join('..', 'data', DATA_FILE_NAME)

DB_NAME = "Tasks.db"


# Generated by shuffle
START_VECTOR = [27, 41, 39, 8, 30, 23, 38, 14, 29, 50, 1, 22, 2, 19, 13, 24, 35, 11, 48, 20, 6, 44, 15, 18, 42, 21, 36,
                7, 4, 49, 3, 17, 45, 28, 31, 33, 40, 25, 26, 12, 16, 37, 34, 32, 10, 9, 43, 46, 47, 5]


def shuffle():  # call only once and save the result!
    x = [i for i in range(50)]
    random.shuffle(x)
    print(x)
    return x


if __name__ == '__main__':
    shuffle()